-- MySQL Script generated by MySQL Workbench
-- Tue Oct 18 22:09:05 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema test_base
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema test_base
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `test_base` DEFAULT CHARACTER SET utf8 ;
USE `test_base` ;

-- -----------------------------------------------------
-- Table `test_base`.`CarBrends`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test_base`.`CarBrends` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `BrendName` VARCHAR(30) NOT NULL,
  `Vehicle` VARCHAR(30) NOT NULL,
  `Coments` VARCHAR(45) NULL COMMENT 'BrendName - for exampe: Opel, Mazda, Daewoo, etc\nVehicle - type of engine and its capacity, for example 1.2, 2.8 biturbo, electro 43kWt\ncomment - other non clasificated information',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test_base`.`Colors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test_base`.`Colors` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ColorName` VARCHAR(25) NOT NULL,
  `ColorCode` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test_base`.`Store`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test_base`.`Store` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `YearOfIssue` INT NULL,
  `ModelYear` INT NULL,
  `AWD` TINYINT(1) NULL,
  `Interior` VARCHAR(45) NULL,
  `ElectroPacket` VARCHAR(45) NULL,
  `Other` VARCHAR(50) NULL,
  `CarBrends_id` INT NOT NULL,
  `Colors_id` INT NOT NULL,
  `BasePrice` DECIMAL(10,2) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Store_CarBrends_idx` (`CarBrends_id` ASC) VISIBLE,
  INDEX `fk_Store_Colors1_idx` (`Colors_id` ASC) VISIBLE,
  CONSTRAINT `fk_Store_CarBrends`
    FOREIGN KEY (`CarBrends_id`)
    REFERENCES `test_base`.`CarBrends` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Store_Colors1`
    FOREIGN KEY (`Colors_id`)
    REFERENCES `test_base`.`Colors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test_base`.`Sales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test_base`.`Sales` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ByerName` VARCHAR(45) NULL DEFAULT 'Unknown byer',
  `OrderDate` DATE NULL,
  `FinalPrice` DECIMAL(10,2) NULL,
  `Store_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Sales_Store1_idx` (`Store_id` ASC) VISIBLE,
  CONSTRAINT `fk_Sales_Store1`
    FOREIGN KEY (`Store_id`)
    REFERENCES `test_base`.`Store` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test_base`.`timestamps`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test_base`.`timestamps` (
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL);

USE `test_base` ;

-- -----------------------------------------------------
-- Placeholder table for view `test_base`.`test_view`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test_base`.`test_view` (`BrendName` INT, `YearOfIssue` INT, `ColorName` INT);

-- -----------------------------------------------------
-- View `test_base`.`test_view`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `test_base`.`test_view`;
USE `test_base`;
CREATE  OR REPLACE VIEW `test_view` AS
    SELECT 
        cb.BrendName, s.YearOfIssue, c.ColorName
    FROM
        CarBrends AS cb,
        Store AS s,
        Colors AS c;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
